### ISSUE TITLE
OpenHPC

### ISSUE THREAD

**Issue by boegel** [FLOSSforScience/crowdsourcingcontent#70]
https://www.hpcwire.com/2018/11/01/openhpc-gathers-steam-preps-new-release-for-sc18/

**Comment by diehlpk** [comment]
@boegel Do you have any contact information or could recommend who we should as for an interview?

**Comment by boegel** [comment]
Karl Schultz would be a good candidate I think, he's sort of the project lead (see @koomie at https://github.com/openhpc/ohpc/graphs/contributors).

Maybe reach out to them via Twitter, see https://twitter.com/OpenHPCcomm .

**Comment by diehlpk** [comment]
@koomie Would you be interested to be interviewed about the OpenHPC project within a series for open source software for HPC?

**Comment by koomie** [comment]
Sure.
