### ISSUE TITLE
Jon Tennant and Open science MOOC : Module 5: Open Research Software and Open Source

### ISSUE THREAD

**Issue by dbrassard** [FLOSSforScience/crowdsourcingcontent#74]
### Name of the organization

@Protohedgehog on Twitter and GitHub

### Contact name and informations

Paleontologist and advocate for open science

Open science MOOC : Module 5: Open Research Software and Open Source
https://eliademy.com/catalog/catalog/product/view/sku/02d7338a7e

**Comment by Protohedgehog** [comment]
Thanks for sharing! Plenty more information here too on GitHub https://github.com/OpenScienceMOOC
