### ISSUE TITLE
Link to email is 404 on new episode page

### ISSUE THREAD

**Issue by doctormo** [FLOSSforScience/crowdsourcingcontent#76]
On page: https://flossforscience.com/podcast/season-2-episode-1

Link: "Martin's Email"

**Comment by dbrassard** [comment]
Fixed by commit -> https://github.com/FLOSSforScience/FLOSSforScience.github.io/commit/1fadac05bbb382b2b66f9bbbd808d80f9de03e01

Thanks :)
